### ISSUE TITLE
unable to find out ruby.h

### ISSUE THREAD

**Issue by ko1** [ruby/rubyspec#120]
https://travis-ci.org/ruby/ruby/jobs/78775640

```
33)

An exception occurred during: loading /Users/travis/build/ruby/ruby/spec/rubyspec/optional/capi/typed_data_spec.rb ERROR

RuntimeError: Unable to compile "/Users/travis/build/ruby/ruby/spec/rubyspec/optional/capi/ext/typed_data_spec.c"

/Users/travis/build/ruby/ruby/spec/rubyspec/optional/capi/spec_helper.rb:79:in `compile_extension'

/Users/travis/build/ruby/ruby/spec/rubyspec/optional/capi/spec_helper.rb:108:in `load_extension'

/Users/travis/build/ruby/ruby/spec/rubyspec/optional/capi/typed_data_spec.rb:3:in `<top (required)>'

/Users/travis/build/ruby/ruby/spec/rubyspec/optional/capi/ext/util_spec.c:1:18: fatal error: ruby.h: No such file or directory

 #include "ruby.h"

                  ^

compilation terminated.

ERROR:

incflags=-I/Users/travis/build/ruby/ruby/spec/rubyspec/optional/capi/ext -I/./include -I/.ext/include/x86_64-darwin13 -I/./include/ruby

cflags= -O3 -fno-fast-math -ggdb3 -Wall -Wextra -Wno-unused-parameter -Wno-parentheses -Wno-long-long -Wno-missing-field-initializers -Wunused-variable -Werror=pointer-arith -Werror=write-strings -Werror=declaration-after-statement -Werror=implicit-function-declaration -Werror=deprecated-declarations -Wno-packed-bitfield-compat  -pipe  -fPIC
```

**Comment by eregon** [comment]
It seems due to a bug of the recent changes to `fake.rb`.
@nobu Can you fix in `fake.rb` and/or in rubyspec if the logic is incorrect?

**Comment by eregon** [comment]
Seems to work now, but the generated config does not seem optimal, in particular:
```ruby
RbConfig::CONFIG["rubyhdrdir"]
# on the failing commit: "/./include"
# on recent commits: "././include"
```

**Comment by ko1** [comment]
Thank you!
