### ISSUE TITLE
On Solaris, some File#flock specs failed

### ISSUE THREAD

**Issue by ngoto** [ruby/rubyspec#122]
On Solaris, some specs about File#flock failed.
On Solaris, the following specs in core/file/flock_spec.rb failed.

```
3)
File#flock returns false if trying to lock an exclusively locked file FAILED
Expected 0
 to equal false

/XXXXX/trunk-51741/spec/rubyspec/core/file/flock_spec.rb:34:in `block (3 levels) in <top (required)>'
/XXXXX/trunk-51741/spec/rubyspec/core/file/flock_spec.rb:33:in `open'
/XXXXX/trunk-51741/spec/rubyspec/core/file/flock_spec.rb:33:in `block (2 levels) in <top (required)>'
/XXXXX/trunk-51741/spec/rubyspec/core/file/flock_spec.rb:3:in `<top (required)>'

4)
File#flock blocks if trying to lock an exclusively locked file FAILED
Expected [:before, :after]
 to equal [:before]

/XXXXX/trunk-51741/spec/rubyspec/core/file/flock_spec.rb:59:in `block (2 levels) in <top (required)>'
/XXXXX/trunk-51741/spec/rubyspec/core/file/flock_spec.rb:3:in `<top (required)>'
```

On Solaris, file locks by using File#flock belong to its process, not belong to file descriptors.
So, flock to the same file in a single process always succeeds.
To examine flock on Solaris, locking a file from different process is needed.

**Comment by ngoto** [comment]
split from https://github.com/ruby/mspec/issues/12
