### ISSUE TITLE
Encoding issue with Dir.glob and Dir.[]

### ISSUE THREAD

**Issue by anthonycrumley** [ruby/rubyspec#56]
These encoding failures are only happening in Ruby 2.2.  Anyone else see this?

```
mspec core/dir/element_reference_spec.rb core/dir/glob_spec.rb
ruby 2.2.2p86 (2015-03-03 revision 49825) [x86_64-darwin14]
[/ | ==================100%================== | 00:00:00]      2F      0E

1)
Dir.[] returns Strings in the encoding of the pattern FAILED
Expected #<Encoding:UTF-8>
 to be identical to #<Encoding:IBM437>

/Users/anthonycrumley/Projects/ruby/spec/rubyspec/core/dir/element_reference_spec.rb:58:in `block (3 levels) in <top (required)>'
/Users/anthonycrumley/Projects/ruby/spec/rubyspec/core/dir/element_reference_spec.rb:39:in `block in <top (required)>'
/Users/anthonycrumley/Projects/ruby/spec/rubyspec/core/dir/element_reference_spec.rb:38:in `<top (required)>'

2)
Dir.glob with encoding returns Strings in the encoding of the pattern FAILED
Expected #<Encoding:UTF-8>
 to be identical to #<Encoding:IBM437>

/Users/anthonycrumley/Projects/ruby/spec/rubyspec/core/dir/glob_spec.rb:50:in `block (4 levels) in <top (required)>'
/Users/anthonycrumley/Projects/ruby/spec/rubyspec/core/dir/glob_spec.rb:29:in `<top (required)>'

Finished in 0.133423 seconds

2 files, 113 examples, 126 expectations, 2 failures, 0 errors
```

**Comment by eregon** [comment]
I do not.

**Comment by benlovell** [comment]
I'm seeing the same when running these specs with 2.2.2. I'm taking a look at this now...

**Comment by eregon** [comment]
Which OS are you on? I think this is platform dependent and might have been already fixed in the MRI ruby_2_2 branch.

**Comment by benlovell** [comment]
OS X.

**Comment by eregon** [comment]
@anthonycrumley @benlovell
My last commit should have fixed the failure,
could you try to run the dir specs on OS X to confirm?

In MRI there is a special path for OS X, which is why the behavior differs between Linux and Darwin.

**Comment by benlovell** [comment]
@eregon I had to make some tweaks. See #69
