### ISSUE TITLE
Failed when using symlink to another disk

### ISSUE THREAD

**Issue by ko1** [ruby/rubyspec#84]
My build environment is a bit strange because I use "/mnt/sdb1/ruby" for another disk and I put link to "/home/ko1/ruby" (ln -s /mnt/sdb1/ruby /home/ko1/ruby).

Recent changes, there are two failed on such an environment.

```
./miniruby -I../../gitruby/lib -I. -I.ext/common  ../../gitruby/tool/runruby.rb --extout=.ext  -- --disable-gems -r./x86_64-linux-fake ../../gitruby/spec/mspec/bin/mspec run -B ../../gitruby/spec/default.mspec
ruby 2.3.0dev (2015-06-17 remove_cf_klass 50935) [x86_64-linux]
last_commit=fix Proc#inspect and so on

1)
The -C command line option changes the PWD when using a file FAILED
Expected "/home/ko1/src/ruby/gitruby/spec/rubyspec/command_line/fixtures"
to equal "/mnt/sdb1/ruby/gitruby/spec/rubyspec/command_line/fixtures"

/mnt/sdb1/ruby/gitruby/spec/rubyspec/command_line/dash_upper_c_spec.rb:12:in `block (2 levels) in <top (required)>'
/mnt/sdb1/ruby/gitruby/spec/rubyspec/command_line/dash_upper_c_spec.rb:3:in `<top (required)>'

2)
The -C command line option changes the PWD when using -e FAILED
Expected "/home/ko1/src/ruby/gitruby/spec/rubyspec/command_line/fixtures"
to equal "/mnt/sdb1/ruby/gitruby/spec/rubyspec/command_line/fixtures"

/mnt/sdb1/ruby/gitruby/spec/rubyspec/command_line/dash_upper_c_spec.rb:18:in `block (2 levels) in <top (required)>'
/mnt/sdb1/ruby/gitruby/spec/rubyspec/command_line/dash_upper_c_spec.rb:3:in `<top (required)>'
...
Finished in 210.856470 seconds

3453 files, 24539 examples, 174262 expectations, 2 failures, 0 errors, 0 tagged
```

Thanks,
Koichi

**Comment by eregon** [comment]
@ko1 Should be fixed, could you confirm?

I have 10 failures related to `require` specs when running in a similar setup, do you see them as well?

**Comment by ko1** [comment]
Thank you for quick fix. I confirm the reported issues are fixed.

And, Yes, I have 10 more failures around $LOAD_FEATURES.

**Comment by eregon** [comment]
I will fix as well.

**Comment by eregon** [comment]
@ko1 Now all specs should *just work*<sup>:tm:</sup>!
(with latest mspec and rubyspec)

**Comment by ko1** [comment]
@eregon Great!
I confirmed it.
